# Generated by Django 2.0.2 on 2018-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_img/default_img.jpg', upload_to='profile/%Y/%m'),
        ),
    ]
